services:
  simdatuk13-api_app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: simdatuk13-api:latest
    container_name: swp_simdatuk13-api
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - "8006:8080"
    networks:
      - dbmysql-network
      - s3minio-network

networks:
  dbmysql-network:
    external: true

  s3minio-network:
    external: true
